runtime: go111
instance_class: F1

handlers:

- url: /.*
  script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic